Configuring a Kubernetes Slave Node

# Install Docker first

add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
apt update
apt-get install -y kubelet kubeadm kubectl kubernetes-cni

# Get the "join" command from the master and enter it here

# Sample command

kubeadm join 10.220.246.26:6443 --token 6p8n06.gn8iec74yritosz5 \
    --discovery-token-ca-cert-hash sha256:639596e995c8984d3eb39b036aaab3e1b1a479a61038793c0bb84733c3d19166

