How to install Kubernetes Master on a Ubuntu 18.04 machine

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add 
add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
apt update
apt-get install -y kubelet kubeadm kubectl kubernetes-cni
kubeadm init

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config
